# Generated by Django 4.0.2 on 2022-03-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_project',
            field=models.ManyToManyField(to='users.User'),
        ),
    ]
