# Generated by Django 4.0.2 on 2022-03-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_project_user_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_project',
            new_name='user_name',
        ),
    ]
