# Generated by Django 4.0.2 on 2022-03-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_project_project_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_name',
            new_name='user_responsible',
        ),
    ]
